apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  type: NodePort
  selector:
    app: vproapp
  ports:
    - port: 80
      targetPort: vproapp-port
      protocol: TCP
      nodePort: 30080

